In [7]:
import pandas as pd
import numpy as np

In [9]:
df=pd.read_csv("Crop_Prediction.csv")

In [10]:
df.head()

,temperature,humidity,ph,rainfall,nitrogen,phosphorus,potassium,soil_moisture,sunlight,crop
0,27.483571,53.643605,6.160753,6.160753,31.0,34.0,75.0,22.538276,7.969427,1
1,24.308678,53.198788,6.347250,198.367205,80.0,9.0,119.0,35.390503,10.250653,1
2,24.995662,33.065352,6.201309,203.214744,17.0,22.0,140.0,32.889249,9.123378,1
3,32.615149,55.048647,6.555209,247.343073,34.0,67.0,143.0,29.835646,11.836223,1
4,23.829233,70.992436,7.098589,162.639135,103.0,139.0,131.0,21.154115,7.817343,0

In [5]:
df.tail()

,temperature,humidity,ph,rainfall,nitrogen,phosphorus,potassium,soil_moisture,sunlight,crop
4995,24.755175,79.516531,6.045174,219.391367,32.0,14.0,149.0,34.413222,9.131232,maize
4996,28.557053,30.024825,7.118575,268.868329,4.0,117.0,65.0,45.309407,7.581194,maize
4997,40.564551,49.420249,6.504287,218.917698,21.0,31.0,55.0,21.913539,7.802187,maize
4998,29.040181,67.436484,6.057945,285.676486,77.0,103.0,41.0,22.415182,6.573483,maize
4999,20.759672,69.665827,6.423107,119.004010,13.0,5.0,71.0,36.551639,6.903142,maize

In [11]:
df.size

50000

In [12]:
df.shape

(5000, 10)

In [13]:
df.describe()

,temperature,humidity,ph,rainfall,nitrogen,phosphorus,potassium,soil_moisture,sunlight,crop
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,24.995662,59.864668,6.504287,201.042908,69.240842,73.964000,104.69200,29.943666,7.969427,0.826800
std,4.863823,14.796425,0.485928,48.954689,39.174796,39.775492,56.26727,10.051327,1.923621,0.594367
min,8.793663,1.163996,4.835248,6.160753,0.000000,5.000000,5.00000,-14.656039,1.144689,0.000000
25%,21.859419,50.408494,6.186480,169.151868,36.000000,40.000000,57.00000,23.435477,6.687908,0.000000
50%,24.995662,59.864668,6.504287,201.080242,69.240842,73.964000,104.69200,29.943666,7.969427,1.000000
75%,28.111666,69.450353,6.813898,233.545115,102.000000,107.000000,153.00000,36.578387,9.224055,1.000000
max,44.631189,112.935828,8.214455,423.954213,139.000000,144.000000,204.00000,67.278333,14.560599,3.000000

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   temperature    5000 non-null   float64
 1   humidity       5000 non-null   float64
 2   ph             5000 non-null   float64
 3   rainfall       5000 non-null   float64
 4   nitrogen       5000 non-null   float64
 5   phosphorus     5000 non-null   float64
 6   potassium      5000 non-null   float64
 7   soil_moisture  5000 non-null   float64
 8   sunlight       5000 non-null   float64
 9   crop           5000 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 390.8 KB

In [7]:
#checking null values
df.isnull().sum()

temperature      250
humidity         250
ph               250
rainfall         250
nitrogen         250
phosphorus       250
potassium        250
soil_moisture    250
sunlight         250
crop               0
dtype: int64

In [56]:
#filling null values
df.fillna(df.mean(numeric_only=True),inplace=True)

In [31]:
df.isnull().sum()

temperature      0
humidity         0
ph               0
rainfall         0
nitrogen         0
phosphorus       0
potassium        0
soil_moisture    0
sunlight         0
crop             0
dtype: int64

In [58]:
#checking duplicates
df.duplicated().sum()

np.int64(0)

In [30]:
#coverting categorical into numeric
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['crop']=le.fit_transform(df['crop'])

In [29]:
df['crop'].unique().size

4

In [28]:
df['crop'].unique()

array([1, 0, 2, 3])

In [27]:
df.columns

Index(['temperature', 'humidity', 'ph', 'rainfall', 'nitrogen', 'phosphorus',
       'potassium', 'soil_moisture', 'sunlight', 'crop'],
      dtype='object')

In [19]:
#split feature and target
X=df.drop('crop',axis=1)
y=df['crop']

In [23]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [24]:
#Normalization
from sklearn.preprocessing import MinMaxScaler
norm=MinMaxScaler()
X_normalized=norm.fit_transform(X)

In [25]:
df.to_csv("Crop_Prediction.csv")